[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:api"
watchPatterns = ["api/**"]

[deploy]
startCommand = "npm run start:api"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"